"""Analysis state module"""

from typing import Annotated, Any, Dict, TypedDict, List

# reduction functions
def add_dicts(d1, d2):
    return {**d1, **d2}

def reduce_str(s1, s2):
    return s1 if s1 != '' else s2

def reduce_int(num1, num2):
    return max(num1, num2)


class ResearchState(TypedDict, total=False):

    company: Annotated[str, reduce_str]  # the company to write the analysis about (user-input)
    topics: List[str]  # the topics to write about (user-input)

    reports: Annotated[Dict[str, Any], add_dicts]  # independent topic-based sections
    task_status: Annotated[Dict[str, Any], add_dicts]  # status of the tasks

    final_report: str  # the final report generated by the coordinator agent

    max_drafts: Annotated[int, reduce_int]  # maximum number of revisions


class TopicState(TypedDict):

    company: Annotated[str, reduce_str]  # the company to write the analysis about (user-input)
    topic: str  # the topic to write about (user-input)
    docs: List[str]  # the documents to analyze
    critique: str  # the summary of the documents
    draft: Dict[str, str]  # the ongoing draft of the full analysis
    draft_number: int  # current revision number
    max_drafts: Annotated[int, reduce_int]  # maximum number of revisions
    task_id: str

    # Shared channels with parent
    reports: Annotated[Dict[str, Any], add_dicts]
    task_status: Annotated[Dict[str, Any], add_dicts]
    
